version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/bidos
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/pre_install.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 2000
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/verify_start.sh
      timeout: 60
      runas: root