version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 600
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
  ValidateService:
    - location: scripts/verify_start.sh
      timeout: 60